name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  api_tests:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Run tests
        run: yarn test:api:ci
        env:
          FORCE_COLOR: 2

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

  e2e_tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Run tests
        run: yarn test:e2e:ci
        env:
          FORCE_COLOR: 2

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

      - name: Save screenshots and trace in case of failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: failure-screenshots-trace
          path: allure-results
  
  generate_report:
    name: Generate report
    runs-on: ubuntu-latest
    if: always()
    needs: [api_tests, e2e_tests]
    permissions:
      contents: write
    steps:
      - name: Download Allure report
        uses: actions/download-artifact@v2
        with:
          name: allure-results

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 5

#TODO: Be able to deploy to gh-pages

      # - name: Deploy report to GitHub Pages
      #   if: always()
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_branch: gh-pages
      #     publish_dir: allure-history
