name: Tests

on:
  pull_request: null
  push:
    branches:
      - main
  workflow_dispatch: null

jobs:
  api_tests:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Run tests
        run: yarn test:api:ci
        env:
          FORCE_COLOR: 2

      - name: Save Playwright Test HTML report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report-api
          path: allure-results

  e2e_tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Run tests
        run: yarn test:e2e:ci
        env:
          FORCE_COLOR: 2

      - name: Save Playwright Test HTML report
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: test-report-e2e
          path: allure-results

      - name: Save screenshots and trace in case of failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: failure-screenshots-trace
          path: allure-results
  
  generate_report:
    name: Generate report
    needs: [api_tests, e2e_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure report
        uses: actions/download-artifact@v2
        with:
          name: allure-results

      - name: Get allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to github pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history