name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  api_tests:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Start ServeRest container
        run: yarn api:start

      - name: Run tests
        run: yarn test:api:ci
        env:
          FORCE_COLOR: 2

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-results-api
          path: allure-results
          retention-days: 10

  e2e_tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Run tests
        run: yarn test:e2e:ci
        env:
          FORCE_COLOR: 2

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-results-e2e
          path: allure-results
          retention-days: 10

  generate_report:
    name: Generate report
    needs: [api_tests, e2e_tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Allure reports from API tests
        uses: actions/download-artifact@v3
        with:
          name: allure-results-api
          path: allure-results

      - name: Download Allure reports from End-to-end tests
        uses: actions/download-artifact@v3
        with:
          name: allure-results-e2e
          path: allure-results

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report gh-actions
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10

      - name: Deploy report to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: allure-history
