name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  api_tests:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Start ServeRest container
        run: yarn api:start

      - name: Run tests
        run: yarn test:api:ci
        env:
          FORCE_COLOR: 2
          LOCAL_URL: http://localhost:3000
          # LOCAL_URL: ${{ secrets.LOCAL_URL }}

      - name: Upload Allure report
      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

  e2e_tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Run tests
        run: yarn test:e2e:ci
        env:
          FORCE_COLOR: 2
          E2E_URL: https://front.serverest.dev
          # E2E_URL: ${{ secrets.E2E_URL }}

      - name: Upload Allure report
      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

  generate_report:
      name: Generate report
      needs: [api_tests, e2e_tests]
      runs-on: ubuntu-latest
      steps:
        - name: Download Allure report
          uses: actions/download-artifact@v1
          with:
            name: allure-results

        - name: Get Allure history
          uses: actions/checkout@v2
          if: always()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages
      
        - name: Allure report gh-actions
          uses: simple-elf/allure-report-action@master
          if: always()
          id: allure-report
          with:
            allure_results: allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history
            keep_reports: 20

        - name: Deploy report to gh-pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
            