name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  api_tests:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Start ServeRest container
        run: yarn api:start

      - name: Run tests
        run: yarn test:api:ci
        env:
          FORCE_COLOR: 2

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

  e2e_tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Run tests
        run: yarn test:e2e:ci
        env:
          FORCE_COLOR: 2

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

      - name: Save screenshots and trace in case of failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: failure-screenshots-trace
          path: test-results
