name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  api_tests:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Start ServeRest locally
        run: docker run -d -p 3000:3000 paulogoncalvesbh/serverest

      - name: Run tests
        run: yarn test:api:ci
        env:
          FORCE_COLOR: 2

      - name: Save Playwright Test HTML report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report-api
          path: reports/index.html

  e2e_tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Run tests
        run: yarn test:e2e:ci
        env:
          FORCE_COLOR: 2

      - name: Save Playwright Test HTML report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report-e2e
          path: reports/index.html

      - name: Save screenshots and trace in case of failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: failure-screenshots-trace
          path: test-results
